### PR TITLE
mesonconf not available on newer distributions  / make SPI work on arm64 bit architecture

### PR DESCRIPTION
**Pull request by bootsy52**

### CODE REVIEW

**Comment by bootsy52** [comment]
As Richard K points out: 

[https://forum.armbian.com/topic/12137-getting-spi-on-rockpi-4-to-work-as-spidev/?do=findComment&comment=89477](https://forum.armbian.com/topic/12137-getting-spi-on-rockpi-4-to-work-as-spidev/?do=findComment&comment=89477)

Instead of (unsigned long) you might choose (intptr_t); specifically, that's the C data type for "an int the same size as a pointer".

@widgetlords Kelsey did you had a chance to look into it?

**Comment by widgetlords** [comment]
@bootsy52 I have not had a chance to test these changes but `uint64_t` should be used instead of `unsigned long` (not guaranteed to be pointer-sized) or `intptr_t` (not guaranteed to be present). We need to make sure that 32-bit compatibility is not broken as that is how the majority of users will be using this library.

**Comment by bootsy52** [comment]
@widgetlords 

I thought it would be correct, as this is what Linus Torvalds uses in it's own spidev_test.c program, which seems to work on all architectures

[https://github.com/torvalds/linux/blob/master/tools/spi/spidev_test.c](https://github.com/torvalds/linux/blob/master/tools/spi/spidev_test.c)

**Comment by widgetlords** [comment]
@bootsy52 That program is over [12 years old](https://github.com/torvalds/linux/commit/22b238bdb93ed2fcb1d627ce81d8a2fcbe24de85). Until recently the Linux kernel could only be compiled by GCC. That does not apply to user space programs, which that linked code is. As stated in the [C spec](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) on page 22 the size of `long` has a _minimum_ of 32-bit and thus has no guarantee of being 64-bit on all conforming compilers. It probably does work as expected on most compilers using `long` but why not have it be guaranteed? The best solution is probably to use the same type as the kernel: https://github.com/torvalds/linux/blob/master/include/uapi/linux/spi/spidev.h which is made available in [types.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/types.h).

We will resolve this issue next week as we will be testing different configurations on Raspberry Pis.

**Comment by bootsy52** [comment]
@widgetlords 
Thanx for the very detailed explanation :-)

**Comment by kamilmuza** [comment]
@bootsy52 Do you plan on updating this pull request?

**Comment by widgetlords** [comment]
Fixed in v2.1.1

**Pull request closed without merging**
